import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/common/sections/header";
import { Instrument_Sans, Inter } from "next/font/google";
import { PageGrid } from "@/components/common/page-grid";

const instrumentSans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets: ["latin"],
  style: ["normal", "italic"],
  display: "swap",
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${instrumentSans.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <PageGrid />
        <Header />
        {children}
      </body>
    </html>
  );
}
